server:
    port: 9998
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:D:/Enviornment/Sqlite Files/2412.sqlite
        #druid
        druid:
            initial-size: 20
            min-idle: 20
            max-active: 100
            max-wait: 10000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 30000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: true
            test-on-return: false
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
        map-underscore-to-camel-case: true
# 日志配置信息
logging:
    level:
        org.flyunion.mapper: debug
        org.apache.ibatis.logging: debug