spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: hinakongqi303@gmail.com
        password: epgk ubxn n rns jtt q
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/flyunion
        username: flyunion
        password: hh2f3TFGw3PXEDaL
        #druid
        druid:
            initial-size: 20
            min-idle: 20
            max-active: 100
            max-wait: 10000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 30000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: true
            test-on-return: false
    data:
        redis:
            port: 6379
            password:
            database: 0
            timeout: 3000ms
            host: localhost
server:
    port: 9999
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
        map-underscore-to-camel-case: true
# 日志配置信息
logging:
    level:
        org.flyunion.mapper: debug
        org.apache.ibatis.logging: debug
redis:
    verify:
        captchaKey: "captcha:"
        tokenKey: "token:"

